### ISSUE TITLE
SKSecurityDescriptor bug when acl offset == 0

### ISSUE THREAD

**Issue by KSebion** [EricZimmerman/MFT#3]
I have been having a problem using MFTECmd on a system.
The problem started with the following error being output:
```
There was an error loading the file! Error: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
```
I learned that the error is occurring because ArgumentOutOfRangeException was being thrown by sdsEntry.SecurityDescriptor.Sacl.AceCount.
I think SKSecurityDescriptor is not correctly handling some bytes in the security descriptor.

Here is the output from BitConverter.ToString(sdsEntry.SecurityDescriptor.RawBytes):
```
01-00-14-BC-14-00-00-00-30-00-00-00-00-00-00-00-00-00-00-00-01-05-00-00-00-00-00-05-15-00-00-00-95-8E-67-A5-94-EC-E5-C7-63-5D-0F-42-25-0A-00-00-01-05-00-00-00-00-00-05-15-00-00-00-95-8E-67-A5-94-EC-E5-C7-63-5D-0F-42-01-02-00-00
```
Here is the SDDL from ConvertSecurityDescriptorToStringSecurityDescriptorW for the bytes:
```
O:S-1-5-21-2775027349-3353734292-1108303203-2597G:S-1-5-21-2775027349-3353734292-1108303203-513D:PAINO_ACCESS_CONTROLS:PAINO_ACCESS_CONTROL
```

**Comment by EricZimmerman** [comment]
Can you send me the file that causes the problem so that I could parse it and find out where it is and then add support?

**Comment by KSebion** [comment]
Sure. The file i attached is actually binary not text.
[sds(vss313).bin.txt](https://github.com/EricZimmerman/MFT/files/3980883/sds.vss313.bin.txt)

**Comment by KSebion** [comment]
I would appreciate it if you removed public access to the file when done.

**Comment by EricZimmerman** [comment]
i downloaded the file and deleted that message

**Comment by EricZimmerman** [comment]
This is resolved. download latest MFTECmd and/or source here
