### ISSUE TITLE
MFT parsers missing from nugget

### ISSUE THREAD

**Issue by agoodhockey** [EricZimmerman/MFT#6]
Hey, 
I have been trying to use the latest nugget release and it seems like some parsers are not in the nugget (SDS, USN, I30).
Can you add them to the nugget?

**Comment by agoodhockey** [comment]
Any update on this?

**Comment by EricZimmerman** [comment]
do you sponsor me on github? it does not appear so.

you can sponsor me and i can prioritize this, or you can wait until i get around to building them.
